using System;
using System.Collections.Generic;

namespace SagHidrolik.Models.ViewModesl
{
    public partial class DboStokgen
    {
        public int Ref { get; set; }
        public int? Masterref { get; set; }
        public string Detay { get; set; }
        public string Sube { get; set; }
        public string Stk { get; set; }
        public string Sta { get; set; }
        public string Stb { get; set; }
        public double? Stgm { get; set; }
        public double? Stgt { get; set; }
        public double? Stcm { get; set; }
        public double? Stct { get; set; }
        public double? Kar { get; set; }
        public string Ozelkod1 { get; set; }
        public string Ozelkod2 { get; set; }
        public string Barkod { get; set; }
        public string Alterstk { get; set; }
        public short? Temins { get; set; }
        public double? Asstok { get; set; }
        public double? Azstok { get; set; }
        public string Odemesekli { get; set; }
        public short? Turu { get; set; }
        public string Dovizc { get; set; }
        public double? Sat11 { get; set; }
        public double? Sat12 { get; set; }
        public double? Sat13 { get; set; }
        public double? Sat14 { get; set; }
        public double? Sat15 { get; set; }
        public double? Sat16 { get; set; }
        public double? Sat17 { get; set; }
        public double? Sat18 { get; set; }
        public double? Sat19 { get; set; }
        public double? Sat110 { get; set; }
        public double? Sat11d { get; set; }
        public double? Sat12d { get; set; }
        public double? Sat13d { get; set; }
        public double? Sat14d { get; set; }
        public double? Sat15d { get; set; }
        public double? Sat16d { get; set; }
        public double? Sat17d { get; set; }
        public double? Sat18d { get; set; }
        public double? Sat19d { get; set; }
        public double? Sat110d { get; set; }
        public string Muhkodu { get; set; }
        public string Kdvkodu { get; set; }
        public string Alteradi { get; set; }
        public double? Indy { get; set; }
        public int? Hsf { get; set; }
        public double? Tvs { get; set; }
        public double? Ks { get; set; }
        public double? Tas { get; set; }
        public double? Bs { get; set; }
        public double? Dev { get; set; }
        public double? Km { get; set; }
        public double? Ek { get; set; }
        public double? Otv { get; set; }
        public string Birim2 { get; set; }
        public double? Anabror2 { get; set; }
        public string Birim3 { get; set; }
        public double? Anabror3 { get; set; }
        public short? Stokkilidi { get; set; }
        public double? Alis11 { get; set; }
        public double? Alis12 { get; set; }
        public double? Alis13 { get; set; }
        public double? Alis14 { get; set; }
        public double? Alis15 { get; set; }
        public double? Alis11d { get; set; }
        public double? Alis12d { get; set; }
        public double? Alis13d { get; set; }
        public double? Alis14d { get; set; }
        public double? Alis15d { get; set; }
        public double? Field11 { get; set; }
        public double? Field12 { get; set; }
        public double? Field13 { get; set; }
        public short? Field14 { get; set; }
        public short? Field15 { get; set; }
        public string Field16 { get; set; }
        public string Field17 { get; set; }
        public string Field18 { get; set; }
        public string Field19 { get; set; }
        public string Field20 { get; set; }
        public string Barkod2 { get; set; }
        public string Barkod3 { get; set; }
        public string Ask1 { get; set; }
        public string Aska1 { get; set; }
        public string Ask2 { get; set; }
        public string Aska2 { get; set; }
        public double? Birim1neta { get; set; }
        public double? Birim1grosa { get; set; }
        public double? Birim2neta { get; set; }
        public double? Birim2grosa { get; set; }
        public double? Birim3neta { get; set; }
        public double? Birim3grosa { get; set; }
        public string Grup1 { get; set; }
        public string Grup2 { get; set; }
        public string Grup3 { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string Renk { get; set; }
        public string Beden { get; set; }
        public string Bos1 { get; set; }
        public string Aciklama { get; set; }
        public double? Asgm { get; set; }
        public double? Ascm { get; set; }
        public double? Psgm { get; set; }
        public double? Pscm { get; set; }
        public string Ugmkod { get; set; }
        public string Uretimrec { get; set; }
        public string Secili { get; set; }
        public short? Tur { get; set; }
        public string Dimmheskodu { get; set; }
        public string Dimmyanhes { get; set; }
        public double? Ksgm { get; set; }
        public double? Kscm { get; set; }
        public double? Bzgm { get; set; }
        public double? Bzcm { get; set; }
        public double? Argm { get; set; }
        public double? Arcm { get; set; }
        public double? Urgm { get; set; }
        public double? Urcm { get; set; }
        public double? Spgm { get; set; }
        public double? Spcm { get; set; }
        public double? Uretimmiktari { get; set; }
        public int? Opref { get; set; }
        public string Bbirim { get; set; }
        public double? Bbmiktar { get; set; }
        public int? Uretimdvzcins { get; set; }
        public double? Uretimbrfiyattl { get; set; }
        public double? Uretimbrfiyatdvz { get; set; }
        public double? Urgt { get; set; }
        public double? Urct { get; set; }
        public double? Ksgt { get; set; }
        public double? Ksct { get; set; }
        public double? Bzgt { get; set; }
        public double? Bzct { get; set; }
        public double? Argt { get; set; }
        public double? Arct { get; set; }
        public double? Sipgt { get; set; }
        public double? Sipct { get; set; }
        public double? Kdv { get; set; }
        public short? Stoktip { get; set; }
        public double? Bakmiktar { get; set; }
        public string Resim { get; set; }
        public string Tevkorani { get; set; }
        public int? Int1 { get; set; }
        public int? Int2 { get; set; }
        public int? Int3 { get; set; }
        public int? Int4 { get; set; }
        public int? Int5 { get; set; }
        public double? Dbl1 { get; set; }
        public double? Dbl2 { get; set; }
        public double? Dbl3 { get; set; }
        public double? Dbl4 { get; set; }
        public double? Dbl5 { get; set; }
        public string Str1 { get; set; }
        public string Str2 { get; set; }
        public string Str3 { get; set; }
        public string Str4 { get; set; }
        public string Str5 { get; set; }
        public DateTime? Tarih1 { get; set; }
        public DateTime? Tarih2 { get; set; }
        public DateTime? AktarTarih { get; set; }
        public int? AktarSube { get; set; }
        public int? AktarRefno { get; set; }
        public string AktaKullanici { get; set; }
        public string Masterstk { get; set; }
        public string Mastersta { get; set; }
        public double? Kulmiktar { get; set; }
        public double? Sat21 { get; set; }
        public double? Sat22 { get; set; }
        public double? Sat23 { get; set; }
        public double? Sat24 { get; set; }
        public double? Sat25 { get; set; }
        public double? Sat26 { get; set; }
        public double? Sat27 { get; set; }
        public double? Sat28 { get; set; }
        public double? Sat29 { get; set; }
        public double? Sat210 { get; set; }
        public double? Sat21d { get; set; }
        public double? Sat22d { get; set; }
        public double? Sat23d { get; set; }
        public double? Sat24d { get; set; }
        public double? Sat25d { get; set; }
        public double? Sat26d { get; set; }
        public double? Sat27d { get; set; }
        public double? Sat28d { get; set; }
        public double? Sat29d { get; set; }
        public double? Sat210d { get; set; }
        public double? Sat31 { get; set; }
        public double? Sat32 { get; set; }
        public double? Sat33 { get; set; }
        public double? Sat34 { get; set; }
        public double? Sat35 { get; set; }
        public double? Sat36 { get; set; }
        public double? Sat37 { get; set; }
        public double? Sat38 { get; set; }
        public double? Sat39 { get; set; }
        public double? Sat310 { get; set; }
        public double? Sat31d { get; set; }
        public double? Sat32d { get; set; }
        public double? Sat33d { get; set; }
        public double? Sat34d { get; set; }
        public double? Sat35d { get; set; }
        public double? Sat36d { get; set; }
        public double? Sat37d { get; set; }
        public double? Sat38d { get; set; }
        public double? Sat39d { get; set; }
        public double? Sat310d { get; set; }
        public string P1 { get; set; }
        public string P2 { get; set; }
        public int? Stokuret { get; set; }
        public DateTime? Gtar { get; set; }
        public int? Stokuret2 { get; set; }
        public string P_ID { get; set; }
        public double? Alis21 { get; set; }
        public double? Alis22 { get; set; }
        public double? Alis23 { get; set; }
        public double? Alis24 { get; set; }
        public double? Alis25 { get; set; }
        public double? Alis21d { get; set; }
        public double? Alis22d { get; set; }
        public double? Alis23d { get; set; }
        public double? Alis24d { get; set; }
        public double? Alis25d { get; set; }
        public double? Alis31 { get; set; }
        public double? Alis32 { get; set; }
        public double? Alis33 { get; set; }
        public double? Alis34 { get; set; }
        public double? Alis35 { get; set; }
        public double? Alis31d { get; set; }
        public double? Alis32d { get; set; }
        public double? Alis33d { get; set; }
        public double? Alis34d { get; set; }
        public double? Alis35d { get; set; }
        public int? Aktarim { get; set; }
        public int? Fantom { get; set; }
        public double? Fireorani { get; set; }
        public string Grupno { get; set; }
        public int? Anagrup { get; set; }
        public string Kullanici { get; set; }
        public string Gorunsun { get; set; }
        public double? Freegiris { get; set; }
        public double? Freecikis { get; set; }
        public double? Freebakiye { get; set; }
        public double? Girisone { get; set; }
        public double? Cikisone { get; set; }
        public double? Giristwo { get; set; }
        public double? Cikistwo { get; set; }
        public double? Gtutarone { get; set; }
        public double? Ctutarone { get; set; }
        public double? Gtutartwo { get; set; }
        public double? Ctutartwo { get; set; }
        public string Serinokullan { get; set; }
        public double? Sotvbrftl { get; set; }
        public double? Sotvbrfd { get; set; }
        public double? Sotvodeneny { get; set; }
    }
}
